USE cl202195;

ALTER TABLE emp_clientes
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_leads
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_contratos
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_unidades
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_atividades
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_contrato_unidades
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_usuarios
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE emp_sessoes
  MODIFY COLUMN criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
